### ISSUE TITLE
Error when adding search-ui to next.js project on code sandbox

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#278]
regeneratorRuntime is not defined
ReferenceError: regeneratorRuntime is not defined
    at /sandbox/node_modules/@elastic/search-ui-app-search-connector/lib/AppSearchAPIConnector.js:135:7
    at /sandbox/node_modules/@elastic/search-ui-app-search-connector/lib/AppSearchAPIConnector.js:176:6
    at Object.<anonymous> (/sandbox/node_modules/@elastic/search-ui-app-search-connector/lib/AppSearchAPIConnector.js:241:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/@elastic/search-ui-app-search-connector/lib/index.js:263:53)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by JasonStoltz** [comment]
To work around this, I had to `import "@babel/polyfill";` at the very top of my fie before importing search-ui.

**Comment by JasonStoltz** [comment]
One thought, is that I am not including this in the entrypoint for the `react-search-ui` library, which is causing the issue.

**Comment by JasonStoltz** [comment]
Actually, I think it's the other way around:

It happens on this import:

import AppSearchAPIConnector from "@elastic/search-ui-app-search-connector";

But not on any of these:

import {
 SearchProvider,
 Results,
 SearchBox,
 ErrorBoundary,
 WithSearch
} from "@elastic/react-search-ui";
import { Layout } from "@elastic/react-search-ui-views";

Maybe I'm just doing something wrong in the app search conector

**Comment by FokkeZB** [comment]
Ah, yes.. forgot to report that. I used the same workaround.

**Comment by yakhinvadim** [comment]
This might have something to do with @babel/polyfill being deprecated: https://babeljs.io/docs/en/babel-polyfill
![image](https://user-images.githubusercontent.com/11838280/61145731-92764500-a4ae-11e9-8bf5-f0425e917aa4.png)

**Comment by yakhinvadim** [comment]
To workaround this in Vue, I had to add `import "regenerator-runtime/runtime";` before importing the AppSearchAPIConnector

**Comment by JasonStoltz** [comment]
Relates to #290

**Comment by FokkeZB** [comment]
Since 1.0.0 with #340 in it, I no longer need any import and it just works out of the box. So I guess we can close this issue? Thanks!

**Comment by JasonStoltz** [comment]
@FokkeZB Hey, sorry, I thought merging that PR would have closed this issue. Yes, that should fix this issue. Thanks for following up!
