### ISSUE TITLE
Deployment to a node server fails with error: ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by ehsan-uberleads** [elastic/search-ui#864]
**Describe the bug**
Deployed the following code snippet to a node server (to either Azure App Service as well as Azure Functions and it failed with the following error:

Code:
```js
const connector = new ElasticsearchAPIConnector({
        cloud: {
            id: process.env.ELASTIC_ID
        },
        apiKey: process.env.ELASTIC_APIKEY,
        index: process.env.ELASTIC_INDEX
    });

    const { queryConfig, requestState } = req.body;
    const response = await connector.onAutocomplete(requestState, queryConfig);
    
    context.res = {
        body: response
    };
```

Result:
```html
<h1>fetch is not defined</h1>
<h2></h2>
<pre>ReferenceError: fetch is not defined
    at FetchClientTransporter.&lt;anonymous&gt; (/home/site/wwwroot/node_modules/@searchkit/sdk/lib/cjs/transporters/FetchClientTransporter.js:20:13)
    at Generator.next (&lt;anonymous&gt;)
    at /home/site/wwwroot/node_modules/@searchkit/sdk/lib/cjs/transporters/FetchClientTransporter.js:8:71
    at new Promise (&lt;anonymous&gt;)
    at __awaiter (/home/site/wwwroot/node_modules/@searchkit/sdk/lib/cjs/transporters/FetchClientTransporter.js:4:12)
    at FetchClientTransporter.performRequest (/home/site/wwwroot/node_modules/@searchkit/sdk/lib/cjs/transporters/FetchClientTransporter.js:19:16)
    at SearchkitRequest.&lt;anonymous&gt; (/home/site/wwwroot/node_modules/@searchkit/sdk/lib/cjs/index.js:125:53)
    at Generator.next (&lt;anonymous&gt;)
    at /home/site/wwwroot/node_modules/@searchkit/sdk/lib/cjs/index.js:18:71
    at new Promise (&lt;anonymous&gt;)</pre>
```

Here's my `package.json` dependencies:
```json
"dependencies": {
    "@elastic/search-ui-elasticsearch-connector": "^1.18.0",
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "debug": "~2.6.9",
    "dotenv": "^16.0.2",
    "ejs": "^3.1.8",
    "express": "~4.16.1",
    "http-errors": "~1.6.3",
    "morgan": "~1.9.1",
    "node-fetch": "^2.6.7"
  }
```

It seems like the `@searchkit/sdk` has not been packaged with `node-fetch` for nodejs server side support. any ideas how to get over this?

**Comment by joemcelroy** [comment]
hi @ehsan-uberleads, you will need to add the polyfill for fetch. Behind the scenes its using Searchkit and in the below example, its using the cross-fetch library to add fetch support.

`import 'cross-fetch/polyfill';`

https://codesandbox.io/s/searchkit-node-js-express-js-example-c7bk7e?file=/src/index.ts:64-94

An ex

**Comment by ehsan-uberleads** [comment]
Thank you!

**Comment by ZakKa89** [comment]
Had the same issue, here is the part of the elastic docs with the polyfill example:
https://docs.elastic.co/search-ui/api/connectors/elasticsearch#nodejs-integration
